add tiktok
IDN-Media/instagram-connect.ice.id pull request #4
Opened 2024-01-24 05:51 UTC by masnasri-a

2024-01-24 06:24 UTC, aufalm requested changes

2024-01-24 06:24 UTC, aufalm commented on server.js
> +    // res.json(profileResponse);
kurang ngecek ke API 
`${process.env.INFLUENCER_API_URL}/influencer/platform/validation?platformName=Instagram&username=`
untuk validasi username sudah pernah connect di akun lain atau belum

2024-01-24 06:24 UTC, aufalm commented on server.js
> +    // res.json(profileResponse);
jika sudah maka return isValid false, sama kyk yg facebook

2024-01-24 06:24 UTC, aufalm commented on server.js
> +    res.json(mapper);
response nya:
`status: 200
data:
   username:
   ....`

2024-01-29 02:53 UTC, masnasri-a commented
tak gabung di branch engagement rate mas di sekalianin

2024-01-29 02:53 UTC, closed without merging