Feat/engagement rate ig
IDN-Media/instagram-connect.ice.id pull request #5
Opened 2024-01-27 10:51 UTC by masnasri-a

2024-01-29 05:48 UTC, aufalm requested changes

2024-01-29 05:48 UTC, aufalm commented on server.js
> +      redirect_uri: 'https://pi3wrvhm6e.ap-southeast-1.awsapprunner.com/login-callback/'
pake env

2024-01-29 05:57 UTC, nanas-a commented on server.js
> +      redirect_uri: 'https://pi3wrvhm6e.ap-southeast-1.awsapprunner.com/login-callback/'
ohhh oke mas

2024-01-29 08:10 UTC, masnasri-a commented on server.js
> +      redirect_uri: process.env.TIKTOK_REDIRECT_URI,
has moved to env

2024-01-29 14:08 UTC, aufalm approved these changes

2024-01-30 02:09 UTC, ahmadsujana approved these changes

2024-01-30 11:33 UTC, merged